/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vota.h"

bool_t
xdr_Input (XDR *xdrs, Input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->cand, MAXS))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->op))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Show (XDR *xdrs, Show *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->candidato, MAXS))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->giudice, MAXS))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->categoria))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nomeFile, MAXS))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->fase))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->voto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Tab (XDR *xdrs, Tab *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->show, N,
		sizeof (Show), (xdrproc_t) xdr_Show))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Nome (XDR *xdrs, Nome *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->c, MAXS))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Elenco (XDR *xdrs, Elenco *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nome, N,
		sizeof (Nome), (xdrproc_t) xdr_Nome))
		 return FALSE;
	return TRUE;
}
