/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOTA_H_RPCGEN
#define _VOTA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define N 7
#define NUMCOL 6
#define MAXS 256

struct Input {
	char *cand;
	char *op;
};
typedef struct Input Input;

struct Show {
	char *candidato;
	char *giudice;
	char categoria;
	char *nomeFile;
	char fase;
	int voto;
};
typedef struct Show Show;

struct Tab {
	Show show[N];
};
typedef struct Tab Tab;

struct Nome {
	char *c;
};
typedef struct Nome Nome;

struct Elenco {
	Nome nome[N];
};
typedef struct Elenco Elenco;

#define VOTA 0x20000013
#define VOTAVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CLASSIFICA_GIUDICI 2
extern  Elenco * classifica_giudici_1(void *, CLIENT *);
extern  Elenco * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO 1
extern  int * esprimi_voto_1(Input *, CLIENT *);
extern  int * esprimi_voto_1_svc(Input *, struct svc_req *);
extern int vota_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CLASSIFICA_GIUDICI 2
extern  Elenco * classifica_giudici_1();
extern  Elenco * classifica_giudici_1_svc();
#define ESPRIMI_VOTO 1
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
extern int vota_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Show (XDR *, Show*);
extern  bool_t xdr_Tab (XDR *, Tab*);
extern  bool_t xdr_Nome (XDR *, Nome*);
extern  bool_t xdr_Elenco (XDR *, Elenco*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_Show ();
extern bool_t xdr_Tab ();
extern bool_t xdr_Nome ();
extern bool_t xdr_Elenco ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VOTA_H_RPCGEN */
