/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operazioni.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

FS_Out *
file_scan_1(argp, clnt)
	char **argp;
	CLIENT *clnt;
{
	static FS_Out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, FILE_SCAN, xdr_wrapstring, argp, xdr_FS_Out, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
dir_scan_1(argp, clnt)
	DirScan_In *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DIR_SCAN, xdr_DirScan_In, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
