/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operazioni.h"

bool_t
xdr_FS_Out(xdrs, objp)
	XDR *xdrs;
	FS_Out *objp;
{

	if (!xdr_int(xdrs, &objp->numChar))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->numWords))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->numLines))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_DirScan_In(xdrs, objp)
	XDR *xdrs;
	DirScan_In *objp;
{

	if (!xdr_string(xdrs, &objp->direttorio, 50))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->soglia))
		return (FALSE);
	return (TRUE);
}
